---
title: "calendar"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{calendar}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(rjd3toolkit)
```

```{r}
GaliciaCalendar <- list(
  fixed_day(month = 3, day = 19, validity = list(start = "1995-03-19", end="1995-04-19")),
  fixed_day(month = 3, day = 19, validity = list(start = "1998-01-01", end="1999-12-31")),
  fixed_day(month = 6, day = 24, validity = list(start = "2013-01-01", end="2013-12-31")),
  fixed_day(month = 6, day = 24, validity = list(start = "2016-01-01", end="2016-12-31")),
  fixed_day(month = 6, day = 24, validity = list(start = "2020-01-01", end="2020-12-31")),
  
  single_day("1995-03-19"),
  single_day("1998-03-19"),
  single_day("1999-03-19")
)

Days_off <- holidays(GaliciaCalendar, "1960-01-01", 365.25*140, nonworking=7, type="All",single = TRUE)
Days_off["1960-03-19",] # It is considering the days off defined for 1995 and 1998
Days_off["1960-06-24",] # It is considering the days off defined for 2013, 2016 and 2020

calendar <- list(
  fixed_day(month = 3, day = 19, validity = list(start = "1995-03-19", end="1995-04-19"))
)
head(holidays(calendar, "1996-03-10", 365.25*140, nonworking=7, type="All",single = TRUE), 10)

# Equivalent to
calendar <- list(
  single_day("1995-03-19")
)
```



